baseURL: "https://chvmuralikumar-profile.netlify.app/"
languageCode: "en-us"
title: "CH V Muralikumar - Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    #- identifier: blog
    # name: Blog
    # title: Blog posts
    # url: /blogs
    # weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "CH V Muralikumar - Profile"
  description: CH V Muralikumar - Profile
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "CH V Muralikumar - Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Muralikumar."
    subtitle: "Pricipal Java Developer"
    content: "Highly motivated and experienced software professional with over 15+ years of experience in Java and Microsoft Azure. Adept at using Java/J2EE, Spring Framework, Hibernate, and various Azure services to develop and deploy secure, scalable, and high performing applications. Excellent problem-solving and communication skills with a strong ability to work in a team environment."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/muralikumarch
        - icon: fab fa-twitter
          url: https://twitter.com/MuralikumarCh
        - icon: fa-brands fa-linkedin
          url: "https://www.linkedin.com/in/chvmuralikumar/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      Highly motivated and experienced software professional with over 15+ years of experience in Java and Microsoft Azure. Adept at using Java/J2EE, Spring Framework, Hibernate, and various Azure services to develop and deploy secure, scalable, and high performing applications. Excellent problem-solving and communication skills with a strong ability to work in a team environment. I am currently working as a principal java developer at [Parexel International (India) Pvt. Ltd.](https://parexel.com) in Hyderabad, India. 

      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java/J2EE"
        - "Spring Framework, Spring boot"
        - "Hibernate, JPA, JDBC, JSP, Servlet"
        - "MySQL, Oracle"
        - "PrimeFaces, JavaScript, HTML, CSS"
        - "Kony Mobile, Flutter, Android"
        - "ANT, Maven, JUnit"
        - "Microsoft Azure"
        - "Problem solving, Communication"
        - "Curious, Organized, Teamwork"


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Pricipal Java Developer"
        company: "Parexel"
        companyUrl: "https://parexel.com"
        date: "Sep 2014 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          I am currently working as a Pricipal Java developer at [Parexel International (India) Pvt. Ltd.](https://parexel.com) in Hyderabad, India. 
          
          - Use Java/J2EE, Spring, Spring boot, Hibernate technologies to develop web applications for client server environments and add functionalities to existing applications.
          - Conduct user requirements analysis to design and program applications and deliver support for system enhancement.
          - Play a pivotal role as a part of an agile scrum team accountable, developing new applications using Spring framework.
          - Involved in development of various stories and bugs of various for VCAS (Virtual Clinical Adjudication System) projects and contribute to other technical documentation activities. Developed UI and Service layer components for various modules.
          - Hands on experience in Azure Development, worked on Azure web application, App services, Azure storage, Azure SQL Database, Virtual machines.
          - Designed, configured, and deployed Microsoft Azure for a multitude of applications utilizing the Azure, focusing on high - availability, fault tolerance, and auto-scaling.
          - Developed methodologies for cloud migration, implemented best practices and helped to develop backup and recovery techniques for applications and database on virtualization platform.

      - job: "Senior Software Engineer"
        company: "Kony"
        companyUrl: "https://kony.com"
        date: "Oct 2013 – Sep 2014"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a senior software engineer for not more than one year in Kony.
        content: |
          I worked as a senior software engineer at [Kony IT Services Pvt Ltd.](https://kony.com) in Hyderabad, India.

          - Involved various mobile apps development with Kony Mobile Platform.
          - in implementing custom features, UI design along with business team
          - Developed and integrated processes into system life cycle management

      - job: "Software Engineer"
        company: "Wipro"
        companyUrl: "https://wipro.com"
        date: "Mar 2010 – Oct 2013"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I worked as a software engineer at [Wipro Technologies ](https://wipro.com) in Hyderabad, India.
          
          - Rendered solid technical expertise in SDLC and various Java/J2EE web application developments with Core Java, JSP, Spring, JBOSS 5 and Oracle 10g.
          - Developed highly interactive and customized UI using JavaScript, HTML, JSP, and CSS to improve functionality of web applications.
          - Performed unit testing of applications by developing and applying test cases in JUnit.

      - job: "Software Engineer"
        company: "N-Dime"
        companyUrl: "https://n-dime.com"
        date: "Oct 2007 – Mar 2010"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I worked as a software engineer at [N-Dime Technologies ](https://n-dime.com) in Hyderabad, India.
          
          - Rendered solid technical expertise in SDLC and various Java/J2EE web application developments with Core Java, JSP, Spring, Tomcat and Oracle.
          - Developed highly interactive and customized UI using JavaScript, HTML, JSP, and CSS to improve functionality of web applications.
          - Performed unit testing of applications by developing and applying test cases in JUnit.
          - Worked in a team of designers, developers, and business specialists.
          - Developed reusable component libraries using J2EE technologies, Spring Framework, Tomcat, and Oracle to save time and increase productivity.

          
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Computer Application(M.C.A)"
        school:
          name: "Andhra University, Vishakapatnam, AP, IN"
          url: "https://example.org"
        date: "2003 - 2006"
        
      - title: "Bachelor of Science(B.Sc.) in Computer Science"
        school:
          name: "Andhra University, Vishakapatnam, AP, IN"
          url: "https://example.org"
        date: "2000 - 2003"
        
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Computer Application(M.C.A)"
        school:
          name: "Andhra University, Vishakapatnam, AP, IN"
          url: "https://example.org"
        date: "2003 - 2006"
        
      - title: "Bachelor of Science(B.Sc.) in Computer Science"
        school:
          name: "Andhra University, Vishakapatnam, AP, IN"
          url: "https://example.org"
        date: "2000 - 2003"


  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: Java SE 8 Programmer(OCP)
        content: From Oracle in 2018
      - title: Java Spring Framework
        content: From Coursera in 2021
      - title: Azure Developer Associate
        content: From Microsoft in 2022
      - title: Azure Solutions Architect Expert
        content: From Microsoft in 2022
      - title: Power Platform App Maker Associate 
        content: From Microsoft in 2022


  #Contact
  contact:
    enable: true
    title: "Contacts"
    content: Have a great product and need a {job profile} or just want to have a chat?
    email: muralikumar.ch@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
